# Generated by Django 4.2.2 on 2024-02-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_vote"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="voter",
            new_name="user",
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="vote",
            name="vote_type",
            field=models.CharField(
                choices=[("upvote", "Upvote"), ("downvote", "Downvote")], max_length=10
            ),
        ),
    ]
