# Generated by Django 4.2.2 on 2024-02-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_vote_id_vote_vote_id_alter_vote_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
