# Generated by Django 4.2.2 on 2024-02-14 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("blog", "0005_delete_vote"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("vote_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("U", "Up Vote"), ("D", "Down Vote")], max_length=1
                    ),
                ),
                ("voter", models.CharField(max_length=100)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
