# Generated by Django 4.2.2 on 2024-02-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="vote_type",
            field=models.IntegerField(choices=[(1, "Upvote"), (-1, "Downvote")]),
        ),
    ]
